insert into public.food_safety_items
  (food_name, normalized_name, species, safety_level, description, source)
values
  ('chocolate', 'chocolate', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('uvas', 'uvas', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('grapes', 'grapes', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('pasas', 'pasas', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('raisins', 'raisins', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cebolla', 'cebolla', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('onion', 'onion', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('ajo', 'ajo', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('garlic', 'garlic', 'dog', 'toxic', 'Alimento peligroso o potencialmente toxico para perros. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('xilitol', 'xilitol', 'dog', 'toxic', 'Edulcorante peligroso para perros. Evitar por completo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('xylitol', 'xylitol', 'dog', 'toxic', 'Edulcorante peligroso para perros. Evitar por completo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('alcohol', 'alcohol', 'dog', 'toxic', 'Sustancia peligrosa. Evitar por completo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cafe', 'cafe', 'dog', 'toxic', 'La cafeina puede ser peligrosa para perros. Evitar.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('caffeine', 'caffeine', 'dog', 'toxic', 'La cafeina puede ser peligrosa para perros. Evitar.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('aguacate', 'aguacate', 'dog', 'caution', 'Puede requerir precaucion, moderacion o consulta veterinaria.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('avocado', 'avocado', 'dog', 'caution', 'Puede requerir precaucion, moderacion o consulta veterinaria.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('huevo cocido', 'huevo cocido', 'dog', 'caution', 'Puede requerir moderacion y preparacion adecuada.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('yogur natural', 'yogur natural', 'dog', 'caution', 'Puede no sentar bien a algunos animales. Usar moderacion.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('pollo cocido sin huesos', 'pollo cocido sin huesos', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cooked chicken without bones', 'cooked chicken without bones', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('zanahoria', 'zanahoria', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('carrot', 'carrot', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('arroz', 'arroz', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('rice', 'rice', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('calabaza', 'calabaza', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('pumpkin', 'pumpkin', 'dog', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('manzana sin semillas', 'manzana sin semillas', 'dog', 'safe', 'Alimento considerado seguro si se retiran semillas y partes no adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('apple without seeds', 'apple without seeds', 'dog', 'safe', 'Alimento considerado seguro si se retiran semillas y partes no adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('chocolate', 'chocolate', 'cat', 'toxic', 'Alimento peligroso o potencialmente toxico para gatos. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cebolla', 'cebolla', 'cat', 'toxic', 'Alimento peligroso o potencialmente toxico para gatos. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('onion', 'onion', 'cat', 'toxic', 'Alimento peligroso o potencialmente toxico para gatos. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('ajo', 'ajo', 'cat', 'toxic', 'Alimento peligroso o potencialmente toxico para gatos. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('garlic', 'garlic', 'cat', 'toxic', 'Alimento peligroso o potencialmente toxico para gatos. Evitar su consumo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('alcohol', 'alcohol', 'cat', 'toxic', 'Sustancia peligrosa. Evitar por completo.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cafe', 'cafe', 'cat', 'toxic', 'La cafeina puede ser peligrosa para gatos. Evitar.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('caffeine', 'caffeine', 'cat', 'toxic', 'La cafeina puede ser peligrosa para gatos. Evitar.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('uvas', 'uvas', 'cat', 'caution', 'Puede requerir precaucion, moderacion o consulta veterinaria.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('grapes', 'grapes', 'cat', 'caution', 'Puede requerir precaucion, moderacion o consulta veterinaria.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('leche', 'leche', 'cat', 'caution', 'Puede no sentar bien a algunos gatos. Usar moderacion.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('milk', 'milk', 'cat', 'caution', 'Puede no sentar bien a algunos gatos. Usar moderacion.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('atun con moderacion', 'atun con moderacion', 'cat', 'caution', 'Puede formar parte puntual de la dieta, pero no debe ser base alimentaria sin criterio veterinario.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('tuna in moderation', 'tuna in moderation', 'cat', 'caution', 'Puede formar parte puntual de la dieta, pero no debe ser base alimentaria sin criterio veterinario.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('huevo cocido', 'huevo cocido', 'cat', 'caution', 'Puede requerir moderacion y preparacion adecuada.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('pollo cocido sin huesos', 'pollo cocido sin huesos', 'cat', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('cooked chicken without bones', 'cooked chicken without bones', 'cat', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('calabaza', 'calabaza', 'cat', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.'),
  ('pumpkin', 'pumpkin', 'cat', 'safe', 'Alimento considerado seguro en condiciones normales y cantidades adecuadas.', 'Base local curada para MVP academico. Revisar con fuente veterinaria antes de ampliar.')
on conflict (normalized_name, species) do update set
  food_name = excluded.food_name,
  safety_level = excluded.safety_level,
  description = excluded.description,
  source = excluded.source,
  updated_at = now();
